const detailProps = ["id",
    "special",
    "specialName",
    "evolution",
    "evolvers",
    "captain",
    "sailor",
    "sailorNotes",
    "limit",
    "potential",
    "potentialNotes",
    "support",
    "festAbility",
    "festSpecial",
    "festAttackPattern",
    "festAttackTarget",
    "specialNotes",
    "captainNotes",
    "festResistance",
    "supportNotes",
    "limitNotes",
    "swap",
    "swapNotes",
    "superSpecial",
    "superSpecialCriteria",
    "superSpecialNotes",
    "VSCondition",
    "VSSpecial",
    "festResilience"]

export default detailProps