export interface characterInterface {
    name?: string,
    type?: string,
    class?: string[],
    stars?: number,
    cost?: number,
    combo?: number,
    sockets?: number,
    maxLvl?: number,
    expToMax?: number,
    lvl1HP?: number,
    lvl1ATK?: number,
    lvl1RCV?: number,
    maxHP?: number,
    maxATK?: number,
    maxRCV?: number,
    growthRate?: number,
    id?: number,
}